import React, {useState,useEffect} from 'react';
import {Loader , FormField,CarouselWidget} from '../components'


const RenderCarousels = ({data,title})=>{
    if(data?.length > 0){
        return data.map((item)=>{            
                        return <CarouselWidget key={item._id} {...item} />;
                        });             
    }else{
        return(
            <h2 className='mt-5 font-bold text-xl uppercase text-[#6449ff]'>{title}</h2>
        )
    }
}

const Home = () => {
    const [loading, setloading] = useState(false);
    const [allPosts, setallPosts] = useState(null);
    const [searchText, setsearchText] = useState('');
    const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

    const fetchPosts = async () => {
        setloading(true);
    
        try {
          const response = await fetch('http://localhost:8080/api/v1/post', {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
            },
          });
    
          if (response.ok) {
            const result = await response.json();
            setallPosts(result.data.reverse());
          }
        } catch (err) {
          alert(err);
        } finally {
            setloading(false);
        }
      };


    useEffect(() => {
        fetchPosts();
    }, []);



    const handleSearchChange = (e) => {
      clearTimeout(searchTimeout);
      setsearchText(e.target.value);
  
      setSearchTimeout(
        setTimeout(() => {
          const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
          setSearchedResults(searchResult);
        }, 500),
      );
    };
  

  return (
    <section className='max-w-7xl mx-auto'>

        {/* Headings  */}
        <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
                <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning comics generated by Stable Diffusion AI</p>
        </div>

        {/* Search Bar */}
        <div className="mt-16">
        <FormField
          labelName="Search Comics"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
        </div>

        {/* Cards */}
        <div className="mt-10">
        {
            
        loading ? (
            <div className='flex justify-center items-center'><Loader/></div>
        ) :
        
        (<>
            {searchText && 
            
                (<h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Search results for <span className='text-[#222328]'>{searchText}</span>
                </h2>)
                
            }

            <div className='grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-2 xs:grid-cols-1 grid-cols-1 gap-3'>
                {searchText ? (
                    <RenderCarousels data={searchedResults}
                    title="No search result result"/>
                ):(
                    <RenderCarousels  data={allPosts} title="No posts"/>
                )}
            </div>
        
        </>) 

        
        }

        </div>
    </section>
  )
}

export default Home